# Assignment

In [84]:
#Import numpy as np

In [4]:
import numpy as np

### Make a python list => [1,2,3,4,5] and Convert it into numpy array and print it

In [6]:
list1=[1,2,3,4,5]
arr=np.array(list1)
arr


array([1, 2, 3, 4, 5])

### Make a python matrix (3 x 3) => [[1,2,3],[4,5,6],[7,8,9]] AND Convert it into numpy array and print it

In [10]:
matrix1=np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix1


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Make a matrix (3 x 3) using built-in methods (like arange(), reshape() etc.):

In [18]:
arr=np.arange(1,18,2)
arr


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17])

In [19]:
matrix=arr.reshape(3,3)
matrix


array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

### Create a numpy array with 10 random numbers from 0 to 10 (there should be few numbers greater than 1)


In [25]:

randno=np.random.randint(0,10,10)
randno

array([7, 4, 9, 8, 0, 8, 3, 7, 0, 1])

### Create numpy array => [1,2,3,4,5] and convert it to 2D array with 5 rows

In [82]:
arr1=np.array([1,2,3,4,5])
arr2=arr1.reshape(5,1)
arr1
arr2

(5, 1)

### Print the shape of the above created array


In [83]:
arr2.shape

(5, 1)

## Create a numpy array with 10 elements in it. Access and print its 3rd, 4th and 9th element.


In [63]:
arr3=np.random.randint(1,50,10)
arr3

array([13, 16, 19, 49, 11, 39, 19, 36, 22,  6])

In [64]:
arr3[2]

19

In [65]:
arr3[3]

49

In [66]:
arr3[8]

22

### Print alternate elements of that array

In [67]:
arr3[::2]

array([13, 19, 11, 19, 22])

### Change last 3 elements into 100 using broadcasting and print

In [68]:
arr3[:6:-1]=100
arr3

array([ 13,  16,  19,  49,  11,  39,  19, 100, 100, 100])

### Create a 5 x 5 matrix (fill it with any element you like), print it.Then print the middle (3 x 3) matrix.


In [80]:
matrix2=np.array(np.random.randint(0,50,25))
arr4=matrix2.reshape(5,5)
arr4

array([[35, 43, 29, 19,  7],
       [ 6, 34,  7, 11, 46],
       [37, 36, 30, 35, 41],
       [ 0, 39, 17, 24, 43],
       [14,  8, 26, 46, 28]])

In [81]:
arr4[1:4,1:4]

array([[34,  7, 11],
       [36, 30, 35],
       [39, 17, 24]])